# anchors
.altherma_base: &altherma_base
  platform: altherma_hub
  altherma_hub_id: altherma_hub_1

.temp: &temp
  <<: *altherma_base
  device_class: temperature
  unit_of_measurement: °C
  state_class: measurement
  accuracy_decimals: 1

.binary: &binary
  <<: *altherma_base

.current: &current
  <<: *altherma_base
  device_class: current
  unit_of_measurement: A
  icon: mdi:current-ac
  state_class: measurement
  accuracy_decimals: 1  

.voltage: &voltage
  <<: *altherma_base
  device_class: voltage
  unit_of_measurement: V
  state_class: measurement

.rps: &rps
  <<: *altherma_base
  unit_of_measurement: rps
  state_class: measurement

.rpm: &rpm
  <<: *altherma_base
  unit_of_measurement: rpm
  state_class: measurement

.text: &text
  <<: *altherma_base

sensor:
  - <<: *temp
    name: R1T-Outdoor air temp.
    register: 0x20
    offset: 0
    convid: 105
    datasize: 2  
  - <<: *temp
    name: Discharge pipe temp.(R2T)
    register: 0x20
    offset: 4
    convid: 105
    datasize: 2 
  - <<: *temp
    name: Suction pipe temp.(R3T)
    register: 0x20
    offset: 6
    convid: 105
    datasize: 2  
  - <<: *temp
    name: Heat exchanger mid-temp.(R5T)
    register: 0x20
    offset: 8
    convid: 105
    datasize: 2  
  - <<: *current
    name: INV primary current (A)
    register: 0x21
    offset: 0
    convid: 105
    datasize: 2  
  - <<: *altherma_base
    name: Pressure
    register: 0xA0
    offset: 6
    convid: 119
    datasize: 2
    device_class: pressure
    unit_of_measurement: bar
    state_class: measurement
    accuracy_decimals: 1  
  - <<: *temp
    name: DHW setpoint
    register: 0x60
    offset: 7
    convid: 105
    datasize: 2  
  - <<: *temp
    name: LW setpoint (main)
    register: 0x60
    offset: 9
    convid: 105
    datasize: 2    
  - <<: *temp
    name: Leaving water temp. before BUH (R1T)
    register: 0x61
    offset: 2
    convid: 105
    datasize: 2 
  - <<: *temp
    name: Leaving water temp. after BUH (R2T)
    register: 0x61
    offset: 4
    convid: 105
    datasize: 2  
  - <<: *temp
    name: Refrig. Temp. liquid side (R3T)
    register: 0x61
    offset: 6
    convid: 105
    datasize: 2 
  - <<: *temp
    name: Inlet water temp.(R4T)
    register: 0x61
    offset: 8
    convid: 105
    datasize: 2
  - <<: *temp
    name: DHW tank temp. (R5T)
    register: 0x61
    offset: 10
    convid: 105
    datasize: 2  
  - <<: *temp
    name: Indoor ambient temp. (R1T)
    register: 0x61
    offset: 12
    convid: 105
    datasize: 2 
  - <<: *temp
    name: RT setpoint
    register: 0x62
    offset: 5
    convid: 105
    datasize: 2  
  - <<: *altherma_base
    name: Flow sensor (l/min)
    register: 0x62
    offset: 9
    convid: 105
    datasize: 2
    unit_of_measurement: l/min
    state_class: measurement
    accuracy_decimals: 1  
  - <<: *altherma_base
    name: Water pressure
    register: 0x62
    offset: 11
    convid: 105
    datasize: 1
    device_class: pressure
    unit_of_measurement: bar
    state_class: measurement
    accuracy_decimals: 1
  - <<: *altherma_base
    name: Water pump signal (0:max-100:stop)
    register: 0x62
    offset: 12
    convid: 152
    datasize: 1
    accuracy_decimals: 1    
  - <<: *current
    name: Current measured by CT sensor of L1
    register: 0x63
    offset: 14
    convid: 161
    datasize: 1
  
  - <<: *current
    name: Current measured by CT sensor of L2
    register: 0x63
    offset: 15
    convid: 161
    datasize: 1
  
  - <<: *current
    name: Current measured by CT sensor of L3
    register: 0x63
    offset: 16
    convid: 161
    datasize: 1
  - <<: *temp
    name: Target delta T heating
    register: 0x64
    offset: 14
    convid: 152
    datasize: 1
  - <<: *temp
    name: Target delta T cooling
    register: 0x64
    offset: 15
    convid: 152
    datasize: 1

binary_sensor:
- <<: *binary
  name: Defrost Operation
  register: 0x10
  offset: 1
  convid: 304
  datasize: 1
- <<: *binary
  name: Thermostat ON/OFF
  register: 0x60
  offset: 2
  convid: 303
  datasize: 1
- <<: *binary
  name: Water flow switch
  register: 0x60
  offset: 11
  convid: 307
  datasize: 1
- <<: *binary
  name: Thermal protector (Q1L) BUH
  register: 0x60
  offset: 11
  convid: 306
  datasize: 1
- <<: *binary
  name: Thermal protector BSH
  register: 0x60
  offset: 11
  convid: 305
  datasize: 1
- <<: *binary
  name: 2way valve(On:Heat_Off:Cool)
  register: 0x60
  offset: 12
  convid: 307
  datasize: 1
- <<: *binary
  name: 3way valve(On:DHW_Off:Space)
  register: 0x60
  offset: 12
  convid: 306
  datasize: 1
- <<: *binary
  name: BSH
  register: 0x60
  offset: 12
  convid: 305
  datasize: 1
- <<: *binary
  name: BUH Step1
  register: 0x60
  offset: 12
  convid: 304
  datasize: 1
- <<: *binary
  name: BUH Step2
  register: 0x60
  offset: 12
  convid: 303
  datasize: 1
- <<: *binary
  name: Water pump operation
  register: 0x60
  offset: 12
  convid: 301
  datasize: 1
- <<: *binary
  name: Reheat ON/OFF
  register: 0x62
  offset: 2
  convid: 307
  datasize: 1
- <<: *binary
  name: Circulation pump operation
  register: 0x62
  offset: 8
  convid: 302
  datasize: 1

text_sensor:
- <<: *text
  name: Operation Mode
  register: 0x10
  offset: 0
  convid: 217
  datasize: 1
- <<: *text
  name: I/U operation mode
  register: 0x60
  offset: 2
  convid: 315
  datasize: 1

